// FacebookScript.js
(function($){
Type.registerNamespace('FacebookScript');FacebookScript.FacebookScript=function(){}
FacebookScript.FacebookScript.logOutOfFacebook=function(eventArgs){FB.logout(function(){
FacebookScript.FacebookScript.userID=null;FacebookScript.FacebookScript.accessToken=null;});}
FacebookScript.FacebookScript.insertFriends=function(eventArgs){var $0={};$0['uid']='ID';var $1=$('#FieldChoices input:checked');$1.each(function($p1_0,$p1_1){
$0[$p1_1.getAttribute('field')]=$p1_1.getAttribute('display');});var $2=new Office.TableData();$2.headers=new Array(1);$2.headers[0]=[];var $dict1=$0;for(var $key2 in $dict1){var $5={key:$key2,value:$dict1[$key2]};$2.headers[0][$2.headers[0].length]=$5.value;}var $3='SELECT '+Object.keys($0).join(',')+' FROM user WHERE uid IN (SELECT uid2 from friend WHERE uid1 = me())';var $4={};$4.q=$3;FB.api('fql',$4,function($p1_0){
$2.rows=new Array($p1_0.data.length);for(var $1_1=0;$1_1<$p1_0.data.length;$1_1++){$2.rows[$1_1]=new Array($2.headers[0].length);for(var $1_2=0;$1_2<$2.headers[0].length;$1_2++){$2.rows[$1_1][$1_2]=$p1_0.data[$1_1][Object.keys($0)[$1_2]]||'null';}}(document.getElementById('profilepic')).src='http://graph.facebook.com/'+$2.rows[0][0]+'/picture';var $1_0={};$1_0.coercionType=Office.CoercionType.Table;Office.context.document.setSelectedDataAsync($2,$1_0,function($p2_0){
if($p2_0.status===Office.AsyncResultStatus.Failed){write($p2_0.error.name + ' : '+$p2_0.error.message);}if($p2_0.status===Office.AsyncResultStatus.Succeeded){var $2_0={};$2_0.id=FacebookScript.FacebookScript.tableBinding;$('#friend').show();$('#insert').hide();Office.context.document.bindings.addFromSelectionAsync(Office.BindingType.Table,$2_0,function($p3_0){
Office.select('bindings#'+FacebookScript.FacebookScript.tableBinding).addHandlerAsync(Office.EventType.BindingSelectionChanged,FacebookScript.FacebookScript.handleTableSelection);});}});});}
FacebookScript.FacebookScript.handleTableSelection=function(args){var $0={};$0.startRow=args.startRow;$0.startColumn=0;$0.rowCount=1;$0.columnCount=1;$0.coercionType=Office.CoercionType.Table;Office.select('bindings#'+FacebookScript.FacebookScript.tableBinding).getDataAsync($0,function($p1_0){
if($p1_0.status===Office.AsyncResultStatus.Succeeded){FacebookScript.FacebookScript.friendID=$p1_0.value.rows[0][0];(document.getElementById('profilepic')).src='http://graph.facebook.com/'+FacebookScript.FacebookScript.friendID+'/picture';}});}
FacebookScript.FacebookScript.handleSelectAllCheckBox=function(eventArgs){var $0=$('#ckbSelectAll').is(':checked');$('#FieldChoices input').each(function($p1_0,$p1_1){
($p1_1).checked=$0;});}
FacebookScript.FacebookScript.postFriendStatus=function(eventArgs){if(FacebookScript.FacebookScript.friendID!=null&&!!FacebookScript.FacebookScript.friendID){var $0={};$0.to=FacebookScript.FacebookScript.friendID;$0.from=FacebookScript.FacebookScript.userID;$0.method='feed';$0.display='page';FB.ui($0,function($p1_0){
document.write($p1_0.post_id);;});}}
FacebookScript.FacebookScript.postToAllFreinds=function(eventArgs){var $0={};$0.filterType=Office.FilterType.OnlyVisible;$0.startColumn=0;$0.columnCount=1;$0.coercionType=Office.CoercionType.Table;Office.select('bindings#'+FacebookScript.FacebookScript.tableBinding).getDataAsync($0,function($p1_0){
var $1_0=[];for(var $1_2=0;$1_2<$p1_0.value.rows.length;$1_2++){$1_0[$1_0.length]=$p1_0.value.rows[$1_2][0];}var $1_1={};$1_1.display='popup';$1_1.method='send';$1_1.to=$1_0.join(',');$1_1.from=FacebookScript.FacebookScript.userID;$1_1.link='';FB.ui($1_1,function($p2_0){
document.write($p2_0.post_id);;});});}
FacebookScript.FacebookScript.setBinding=function(){var $0={};$0.id='TextBinding';Office.context.document.bindings.addFromSelectionAsync(Office.BindingType.Text,$0,function($p1_0){
Office.select('bindings#TextBinding').addHandlerAsync(Office.EventType.BindingDataChanged,FacebookScript.FacebookScript.dataChanged);});}
FacebookScript.FacebookScript.dataChanged=function(args){var $0={};$0.coercionType=Office.CoercionType.Text;Office.select('bindings#TextBinding').getDataAsync($0,function($p1_0){
if($p1_0.status===Office.AsyncResultStatus.Succeeded){$('#selectedDataTxt').val($p1_0.value);}});}
FacebookScript.FacebookScript.registerClass('FacebookScript.FacebookScript');FacebookScript.FacebookScript.userID=null;FacebookScript.FacebookScript.accessToken=null;FacebookScript.FacebookScript.tableBinding='TableBinding';FacebookScript.FacebookScript.friendID=null;(function(){window.fbAsyncInit=function(){
var $1_0={};$1_0.channelUrl='http://facebookagave.azurewebsites.net/pages/channel.ashx';$1_0.appId='263395420459543';$1_0.status=true;$1_0.cookie=false;FB.init($1_0);$('#GetFriends').click(FacebookScript.FacebookScript.insertFriends);$('#LogOut').click(FacebookScript.FacebookScript.logOutOfFacebook);$('#SelectAll').click(FacebookScript.FacebookScript.handleSelectAllCheckBox);$('#postfriendstatus').click(FacebookScript.FacebookScript.postFriendStatus);$('#posttoallfriends').click(FacebookScript.FacebookScript.postToAllFreinds);FB.getLoginStatus(function($p2_0){
if($p2_0.status==='connected'){FacebookScript.FacebookScript.userID=$p2_0.authResponse.userID;FacebookScript.FacebookScript.accessToken=$p2_0.authResponse.accessToken;}else{var $2_0={};$2_0.scope='email,publish_actions,create_event,user_likes,publish_stream,user_about_me,friends_about_me,user_activities,friends_activities,user_birthday,friends_birthday,user_checkins,friends_checkins,user_education_history,friends_education_history,user_events,friends_events,user_groups,friends_groups,user_hometown,friends_hometown,user_interests,friends_interests,user_location,friends_location,user_notes,friends_notes,user_photos,friends_photos,user_questions,friends_questions,user_relationships,friends_relationships,user_relationship_details,friends_relationship_details,user_religion_politics,friends_religion_politics,user_status,friends_status,user_subscriptions,friends_subscriptions,user_videos,friends_videos,user_website,user_work_history,friends_work_history';FB.login(function($p3_0){
FacebookScript.FacebookScript.userID=$p3_0.authResponse.userID;},$2_0);}});};Office.initialize=function($p1_0){
};var $0=document.getElementsByTagName('script')[0];var $1='facebook-jssdk';if($0.id!==$1){var $2=document.createElement('script');$2.id=$1;$2.setAttribute('async',true);$2.src='//connect.facebook.net/en_US/all.js';$0.parentNode.insertBefore($2,$0);}})();
})(jQuery);// This script was generated using Script# v0.7.6.0
