// FacebookScript.js
(function($){
Type.registerNamespace('FacebookScript');FacebookScript.FacebookScript=function(){}
FacebookScript.FacebookScript.checkLogin=function(){FB.getLoginStatus(function($p1_0){
if($p1_0.status==='connected'){alert($p1_0.authResponse.userID);}});}
FacebookScript.FacebookScript.insertFriends=function(eventArgs){var $0='Select first_name, last_name, email, sex from user WHERE uid IN (SELECT uid2 from friend WHERE uid1 = me())';var $1={};$1.q=$0;var $2=new Office.TableData();$2.headers=[['First Name','Last Name','Email','Gender']];FB.api('fql',$1,function($p1_0){
$2.rows=new Array($p1_0.data.length);for(var $1_1=0;$1_1<$p1_0.data.length;$1_1++){$2.rows[$1_1]=new Array(4);$2.rows[$1_1][0]=$p1_0.data[$1_1].first_name;$2.rows[$1_1][1]=$p1_0.data[$1_1].last_name;$2.rows[$1_1][2]=$p1_0.data[$1_1].email;$2.rows[$1_1][3]=$p1_0.data[$1_1].sex;}var $1_0={};$1_0.coercionType=Office.CoercionType.Table;Office.context.document.setSelectedDataAsync($2,$1_0);});}
FacebookScript.FacebookScript.registerClass('FacebookScript.FacebookScript');FacebookScript.FacebookScript.userID=null;FacebookScript.FacebookScript.accessToken=null;Office.initialize=function($p1_0){
var $1_0={};$1_0.channelUrl='http://facebookagave.azurewebsites.net/pages/channel.ashx';$1_0.appId='263395420459543';$1_0.status=true;$1_0.cookie=false;FB.init($1_0);$('#GetFriends').click(FacebookScript.FacebookScript.insertFriends);$('#FBLogin').click(function($p2_0){
var $2_0={};$2_0.scope='email,create_event,user_likes,publish_stream,user_about_me,friends_about_me,user_activities,friends_activities,user_birthday,friends_birthday,user_checkins,friends_checkins,user_education_history,friends_education_history,user_events,friends_events,user_groups,friends_groups,user_hometown,friends_hometown,user_interests,friends_interests,user_location,friends_location,user_notes,friends_notes,user_photos,friends_photos,user_questions,friends_questions,user_relationships,friends_relationships,user_relationship_details,friends_relationship_details,user_religion_politics,friends_religion_politics,user_status,friends_status,user_subscriptions,friends_subscriptions,user_videos,friends_videos,user_website,user_work_history,friends_work_history';FB.login(function($p3_0){
FacebookScript.FacebookScript.userID=$p3_0.authResponse.userID;},$2_0);});FB.getLoginStatus(function($p2_0){
if($p2_0.status==='connected'){FacebookScript.FacebookScript.userID=$p2_0.authResponse.userID;FacebookScript.FacebookScript.accessToken=$p2_0.authResponse.accessToken;}});};Office.initialize(Office.InitializationReason.DocumentOpenend);})(jQuery);// This script was generated using Script# v0.7.6.0
